version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: tomflix_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tomflix_db
    volumes:
      - db_data:/var/lib/mysql

  # ---------------------------------------------------
  # NOVO: Banco de Dados em Memória para a Auditoria
  # ---------------------------------------------------
  redis:
    image: redis:alpine
    container_name: tomflix_redis
    # Não expomos portas para o host (isolamento de segurança)

  # ---------------------------------------------------
  # NOVO: Microsserviço de Logs/Auditoria
  # ---------------------------------------------------
  log-service:
    build: ./log_service
    container_name: tomflix_log_service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  minio:
    image: minio/minio:edge
    container_name: tomflix_minio
    ports:
      - "9000:9000" # Porta da API (Object Storage)
      - "9001:9001" # Porta do Console (Painel Web)
    environment:
      - MINIO_ROOT_USER=admin_tomflix
      - MINIO_ROOT_PASSWORD=SenhaForte123!
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  auth-service:
    build: ./auth_service
    container_name: tomflix_auth_service
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=tomflix_db
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - LOG_URL=http://log-service:4000 # Rota interna para enviar logs de login
    depends_on:
      - db
      - log-service

  app:
    build: .
    container_name: tomflix_app
    ports:
      - "8221:8000" 
    environment:
      - AUTH_URL=http://auth-service:3000
      - LOG_URL=http://log-service:4000 # Rota interna para enviar logs de uso/403
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=tomflix_db
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      # Configurações do Object Storage (MinIO)
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin_tomflix
      - MINIO_SECRET_KEY=SenhaForte123!
      - MINIO_BUCKET_NAME=perfis-tomflix
    depends_on:
      - auth-service
      - db
      - log-service

volumes:
  db_data:
  minio_data: