version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: tomflix_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tomflix_db
    volumes:
      - db_data:/var/lib/mysql

  auth-service:
    build: ./auth_service
    container_name: tomflix_auth_service
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=tomflix_db
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - db

  app:
    build: .
    container_name: tomflix_app
    ports:
      - "8221:8000" 
    environment:
      - AUTH_URL=http://auth-service:3000
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=tomflix_db
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - auth-service
      - db
volumes:
  db_data:
